CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240718203818_init1') THEN
    CREATE TABLE "Voyages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "VoyageEventId" integer NOT NULL,
        CONSTRAINT "PK_Voyages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240718203818_init1') THEN
    CREATE TABLE "VoyageEvents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Description" text NOT NULL,
        "DateAndTime" timestamp with time zone NOT NULL,
        "VoyageId" integer,
        CONSTRAINT "PK_VoyageEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VoyageEvents_Voyages_VoyageId" FOREIGN KEY ("VoyageId") REFERENCES "Voyages" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240718203818_init1') THEN
    CREATE INDEX "IX_VoyageEvents_VoyageId" ON "VoyageEvents" ("VoyageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240718203818_init1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240718203818_init1', '8.0.7');
    END IF;
END $EF$;
COMMIT;

